---
- hosts: all
  name: global configuration
  gather_facts: true
  become: true

  roles:
    - updates

- hosts: nodes
  name: Install and configure Elasticsearch
  gather_facts: true
  become: true
  
  roles:
    - java
    - elasticsearch