---
# RedHat repo setup
- name: Add repository
  template:
    dest: "/etc/yum.repos.d/elasticsearch.repo"
    src: elasticsearch_repo.tmpl
  when: ansible_os_family == "RedHat"

- name: Add repo key
  rpm_key: key=https://packages.elastic.co/GPG-KEY-elasticsearch

# Debian repo setup
- name: Install https transport for apt
  apt: name=apt-transport-https
  when: ansible_os_family == "Debian"

- name: Install datadog repository (Debian)
  apt_repository: repo='deb https://apt.datadoghq.com/ stable main' state=present
  when: ansible_os_family == "Debian"

- name: Install datadog repo apt key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=C7A7DA52
  when: ansible_os_family == "Debian"

# Generic install steps
- name: Install Elasticsearch
  package: name=elasticsearch update_cache=yes

- name: Template Elasticsearch config
  template:
    dest: /etc/elasticsearch/elasticsearch.yml
    src: elasticsearch.yml.tmpl
  notify: restart elasticsearch

- name: Start Elasticsearch service
  service: name=elasticsearch state=started
